env:
  level: "debug"

database:
  dsn: "postgresql://server_user:testpwd123@172.21.144.1:5432/whuclubsynapse?connect_timeout=10&sslmode=disable&application_name=auth_server&search_path=public&client_encoding=UTF8&timezone=UTC"