env:
  level: "debug"

database:
  dsn: "postgresql://server_user:testpwd123@172.21.144.1:5432/whuclubsynapse?connect_timeout=10&sslmode=disable&application_name=auth_server&search_path=public&client_encoding=UTF8&timezone=UTC"

redis:
  host: localhost
  port: 6379
  password: "lbbbbbb"
  db: 0
  max_conn: 10
  min_idle: 3
  max_retries: 3

grpc:
  host: localhost
  port: 50051
  max_conn: 5
  min_conn: 1
  idle_timeout: 60