import type { Club, User } from '@/types'

// 模拟社团数据
export const mockClubs: Club[] = [
  {
    id: '1',
    name: '计算机科学协会',
    description:
      '致力于推广计算机科学知识，组织编程竞赛和技术分享活动。为同学们提供学习交流的平台，提升编程能力和技术水平。',
    coverImage: 'https://picsum.photos/400/240?random=1',
    category: '学术科技',
    adminId: 'admin1',
    adminName: '张三',
    currentMembers: 85,
    maxMembers: 100,
    tags: ['编程', '算法', '竞赛'],
    isHot: true,
    status: 'active',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T15:30:00Z',
    isFavorite: true,
  },
  {
    id: '2',
    name: '摄影艺术社',
    description:
      '用镜头记录美好，用光影诉说故事。我们定期组织外拍活动，分享摄影技巧，举办摄影展览。',
    coverImage: 'https://picsum.photos/400/240?random=2',
    category: '文艺体育',
    adminId: 'admin2',
    adminName: '李四',
    currentMembers: 42,
    maxMembers: 60,
    tags: ['摄影', '艺术', '创作'],
    isHot: false,
    status: 'active',
    createdAt: '2024-01-10T14:00:00Z',
    updatedAt: '2024-01-18T09:15:00Z',
    isFavorite: false,
  },
  {
    id: '3',
    name: '青年志愿者协会',
    description: '奉献爱心，服务社会。组织各类志愿服务活动，传播正能量，为社会贡献青春力量。',
    coverImage: 'https://picsum.photos/400/240?random=3',
    category: '志愿服务',
    adminId: 'admin3',
    adminName: '王五',
    currentMembers: 128,
    maxMembers: 150,
    tags: ['志愿', '公益', '服务'],
    isHot: true,
    status: 'active',
    createdAt: '2024-01-08T16:30:00Z',
    updatedAt: '2024-01-22T11:45:00Z',
    isFavorite: false,
  },
  {
    id: '4',
    name: '创业实践社',
    description: '培养创新思维，践行创业梦想。为有创业想法的同学提供平台，组织创业大赛和项目孵化。',
    coverImage: 'https://picsum.photos/400/240?random=4',
    category: '创新创业',
    adminId: 'admin4',
    adminName: '赵六',
    currentMembers: 35,
    maxMembers: 50,
    tags: ['创业', '创新', '商业'],
    isHot: false,
    status: 'active',
    createdAt: '2024-01-12T08:00:00Z',
    updatedAt: '2024-01-19T14:20:00Z',
    isFavorite: false,
  },
  {
    id: '5',
    name: '篮球社',
    description: '挥洒汗水，释放激情。定期组织篮球训练和比赛，提高球技，增强体质，培养团队精神。',
    coverImage: 'https://picsum.photos/400/240?random=5',
    category: '文艺体育',
    adminId: 'admin5',
    adminName: '孙七',
    currentMembers: 67,
    maxMembers: 80,
    tags: ['篮球', '运动', '团队'],
    isHot: true,
    status: 'active',
    createdAt: '2024-01-05T20:00:00Z',
    updatedAt: '2024-01-25T16:10:00Z',
    isFavorite: false,
  },
  {
    id: '6',
    name: '机器人研究社',
    description: '探索人工智能的奥秘，动手制作智能机器人。参与机器人竞赛，推动科技创新发展。',
    coverImage: 'https://picsum.photos/400/240?random=6',
    category: '学术科技',
    adminId: 'admin6',
    adminName: '周八',
    currentMembers: 28,
    maxMembers: 40,
    tags: ['机器人', '人工智能', '科技'],
    isHot: false,
    status: 'active',
    createdAt: '2024-01-18T12:30:00Z',
    updatedAt: '2024-01-24T10:05:00Z',
    isFavorite: false,
  },
  {
    id: '7',
    name: '音乐社',
    description:
      '用音乐传递情感，用歌声温暖人心。我们有吉他、钢琴、声乐等多个分部，定期举办音乐会。',
    coverImage: 'https://picsum.photos/400/240?random=7',
    category: '文艺体育',
    adminId: 'admin7',
    adminName: '吴九',
    currentMembers: 55,
    maxMembers: 70,
    tags: ['音乐', '演出', '艺术'],
    isHot: false,
    status: 'active',
    createdAt: '2024-01-07T19:15:00Z',
    updatedAt: '2024-01-21T13:40:00Z',
    isFavorite: false,
  },
  {
    id: '8',
    name: '环保行动社',
    description: '保护环境，从我做起。组织环保宣传活动，参与垃圾分类推广，倡导绿色生活方式。',
    coverImage: 'https://picsum.photos/400/240?random=8',
    category: '志愿服务',
    adminId: 'admin8',
    adminName: '郑十',
    currentMembers: 73,
    maxMembers: 90,
    tags: ['环保', '绿色', '公益'],
    isHot: true,
    status: 'active',
    createdAt: '2024-01-14T11:20:00Z',
    updatedAt: '2024-01-23T17:25:00Z',
    isFavorite: false,
  },
]

// 模拟用户数据
export const mockUser: User = {
  id: 'user1',
  username: 'testuser',
  email: 'test@example.com',
  avatar: 'https://avatars.githubusercontent.com/u/1?v=4',
  role: 'student',
  studentId: '2021301111',
  realName: '测试用户',
  college: '计算机学院',
  phone: '13800138000',
  createdAt: '2024-01-01T00:00:00Z',
}

// 分类统计数据
export const mockCategories = {
  学术科技: 15,
  文艺体育: 23,
  志愿服务: 18,
  创新创业: 12,
  其他: 8,
}
